[package]
name = "rust_driver"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
wdk       = "0.4.1"
wdk-sys   = "0.5.1"
wdk-alloc = "0.4.1"
wdk-panic = "0.4.1"

[features]
default = []
nightly = ["wdk/nightly", "wdk-sys/nightly"]

[build-dependencies]
wdk-build = "0.5.1"

[package.metadata.wdk.driver-model]
driver-type = "KMDF"
kmdf-version-major = 1
target-kmdf-version-minor = 33
minimum-kmdf-version-minor = 33

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

